@include('frontend.header')
<body>
<div class="container">
    <div class=" pt-5" style="background-color:#009688">
        <h3>TERMS AND CONDITIONS OF ACCESS OR USE</h3>
    </div>

    <pre>
Effective 24th April 2019

<h4>1.	Introduction</h4>
1.	Vidya Sathi Innovations Private Limited having its registered office at ………………………. (hereinafter referred to as "Vidya Sathi", "we", "us", or "our") provides online courses and conducts online classes (the "Services"), which Services are accessible at www.Vidyasathionline.com and any other websites through which Vidya Sathi makes the Services available (collectively, the "Site") and as applications for mobile, tablet and other smart devices and application program interfaces (collectively, the "Applications").
2.	By accessing or using the Site, Application or Services or by downloading or posting any content from or on the Site, via the Applications, you would be indicating that you have read, and that you understand and agree to be bound by these terms and receive our Services (“Terms of Services” or “Terms”), whether or not you have registered with the Site and/or Application.
3.	Therefore, please read these Terms of service before accessing or using the Site, Application or Services or downloading or posting any content from or on the Site, via the Application or through the Services, carefully as they contain important information regarding your legal rights, remedies and obligations.
4.	If you do not agree to these Terms, then you have no right to access or use the Site, Application, Services, or Collective Content (as defined below).
5.	If you are using the Site, Application or Services then these Terms of Service are binding between you and Vidya Sathi.

<h4>2.	Definition</h4>
In addition to other words and expressions that may be defined elsewhere in these Terms, unless the context otherwise requires, the following capitalized terms wherever used in the Agreement shall have the meanings as ascribed hereunder:
1.	"Courses" means educational courses listed on the Site or Application.
2.	"Course Fees" means the amounts that are due and payable by a Student for enrollment of Course.
3.	"Collective Content" means Member Content and Vidya Sathi Content.
4.	"Content" means text, graphics, images, music, software (excluding the Application), audio, video, information or other materials.
5.	"Listing" means Courses that are listed by Vidya Sathi as available via the Site, Application, and Services.
6.	"Member" means a person, who completes Vidya Sathi’s account registration process, including but not limited to Teachers and Students, as described under "Account Registration" in Clause 7 below.
7.	"Member Content" means all Content that a Member posts, uploads, publishes, submits, transmits, or includes in their Listing, Member profile or Vidya Sathi promotional campaign to be made available through the Site, Application or Services.
8.	"Payment Method" means a payment method that you have added to your Vidya Sathi Account, such as a credit card, debit card or net banking.
9.	"Student" means a Member who enrolls for Courses on Application or Site, in case of minor student the parent or guardian who enroll their child or ward for the Courses on Application or Site.
10.	"Tax" or "Taxes" mean any sales taxes, value added taxes (VAT), goods and services taxes (GST), service tax, that Vidya Sathi may be required by law to collect and remit to governmental agencies, and other similar municipal, state, federal and national indirect or other withholding and personal or corporate income taxes.
11.	“Teacher” means a Member who has been selected by Vidya Sathi in order to provide services through the Site or Application
12.	"Vidya Sathi Content" means all Content that Vidya Sathi makes available through the Site, Application, Services, or its related promotional campaigns and official social media channels, including any Content licensed from a third party, but excluding Student Content.

<h4>3.	Terms of Service</h4>
1.	By using the Site, Applications or Services, you agree to comply with and be legally bound by the terms and conditions of these Terms, whether or not you become a registered user of the Services. These Terms govern your access to and use of the Site, Application and Services and all Collective Content (defined above), and constitute a binding legal agreement between you and Vidya Sathi.The user furhter accepts to allow Vidya Sathi Innovations Private Limited to reach them through call for providing existing services and for providing information on new products and services and will not be subject to DND regulations for such calls.
2.	In addition, certain areas of the Site and Application (and your access to or use of certain aspects of the Services or Collective Content) may have different terms and conditions, standards, guidelines, or policies posted or may require you to agree with and accept additional terms and conditions. If there is a conflict between these Terms and terms and conditions posted for a specific area of the Site, Application, Services, or Collective Content, the latter terms and conditions will take precedence with respect to your use of or access to that area of the Site, Application, Services, or Collective Content.
3.	If you do not agree to these Terms, you have no right to obtain information from or otherwise continue using the Site, Application or Services. Failure to use the Site, Application or Services in accordance with these Terms may subject you to civil and criminal liabilities.
4.	The Site, Application and Services comprise an online platform which creates Listings for Courses and Students may learn about and enrolll for the course directly through the Site and Application.
5.	You acknowledge and agree that, by accessing or using the Site, Application or Services or by downloading or posting any content from or on the Site or via the Application, you are indicating that you have read, and that you understand and agree to be bound by these Terms and receive our Services, whether or not you have registered with the Site and Application. If you do not agree to these terms, then you have no right to access or use the Site, Application, Services, or Collective Content. If you accept or agree to these Terms on behalf of a company or other legal entity, you represent and warrant that you have the authority to bind that company or other legal entity to these Terms and, in such event, "you" and "your" will refer and apply to that company or other legal entity.

<h4> 4.	GDPR COMPLIANCE STATEMENT</h4>
Vidya Sathi respects and complies with the EU General Data Protection Regulations (GDPR). Some of the key ways we comply with these regulations are:
1.	Consent
We explain what you’re consenting to clearly and without ‘legalese’, and ask that you explicitly consent to contact from us.
2.	Breach Notification
In the event of a breach, we will notify affected users within 72 hours of first having become aware of the breach.
3.	Right to Access
Users can request confirmation as to whether or not personal data concerning them is being processed, where and for what purpose. Further, we shall provide a copy of the personal data, in an electronic format.
4.	Right to be Forgotten
Once we have compared your (the subjects') rights to "the public interest in the availability of the data", we may delete your personal data where you have requested this.
5.	Data Portability
We allow you to receive the personal data concerning you, which we will provide in a 'commonly used and machine readable format' and you have the right to transmit that data to another ‘controller’.
6.	Privacy by Design
We implement appropriate technical and organisational measures, in an effective way and protect the rights of data subjects'. We hold and process only the data absolutely necessary for the completion of our duties (data minimisation), as well as limiting the access to personal data to those needing to act out the processing.

<h4> 5.	Eligibility</h4>
Use of the Site, Application and Services is available only to persons who can form legally binding contracts under Nepali laws. The Site, Application and Services are intended solely for persons who are 18 years of age or older. If you are below 18, then your parent or guardian can open an account and help you enroll in courses that are appropriate for you. The use of the Site, Application and Services is also not available to persons whose membership has been suspended or terminated by Vidya Sathi for any reason whatsoever. Any access to or use of the Site, Application or Services by anyone under 18 years is expressly prohibited. By accessing or using the Site, Application or Services you represent and warrant that you are 18 years or older.

<h4> 6.	Usage of Site, Application or Services</h4>
1.	The Site, Application and Services can be used to facilitate the Students to enroll for Courses. Such Courses are included in Listings on the Site, Application and Services by Vidya Sathi. You may view Listings as an unregistered visitor to the Site, Application and Services; however, if you wish to enrolll for the Courses, you must first register to create a Vidya Sathi Account (defined below).
2.	Vidya Sathi makes available an online platform which provides various online Courses for the Students. Unless explicitly specified otherwise in the Vidya Sathi platform, Vidya Sathi's responsibilities are limited to facilitating the availability of the Courses through the Site, Application and Services.

<h4> 7.	Account Registration</h4>
1.	In order to access certain features of the Site and Application, and to enroll for Courses, you must register to create an account ("Vidya Sathi Account") and become a Member. You may register to join the Services directly via the Site or Application or as described in this section. A Teacher is also

Your Vidya Sathi Account and your Vidya Sathi Account profile page will be created for your use of the Site and Application based upon the personal information you provide to us or that we obtain via an SNS as described above. You may not have more than one (1) active Vidya Sathi Account. You agree to provide accurate, current and complete information during the registration process and to update such information to keep it accurate, current and complete. Vidya Sathi reserves the right to suspend or terminate your Vidya Sathi Account and your access to the Site, Application and Services if you create more than one (1) Vidya Sathi Account, or if any information provided during the registration process or thereafter proves to be inaccurate, fraudulent, not current, incomplete, or otherwise in violation of these Terms.
4.	You are responsible for safeguarding your password. You agree that you will not disclose your password to any third party and that you will take sole responsibility for any activities or actions under your Vidya Sathi Account, whether or not you have authorized such activities or actions. You will immediately notify Vidya Sathi of any unauthorized use of your Vidya Sathi Account.

<h4> 8.	Course Listings</h4>
1.	Vidya Sathi will create Listing of various online Courses and the details about the Course, including, but not limited to, the subject, topic, number of sessions, mode of conduct, and time slots of the lectures and pricing and related rules and financial terms will be listed on the Site and the Application. Listings will be made publicly available via the Site, Application and Services. You understand and agree that the placement or ranking of Listings in search results may depend on a variety of factors, including, but not limited to Students preferences, ratings.
2.	Students will be able to view Courses via the Site, Application and Services based upon the information provided in the Listing, Students requirements, and Students' search parameters and preferences. We understand and agree that once a Student requests enrollment for Course, We may not request the Student to pay a higher price than that mentioned in the Site or Application.
3.	Please note that Vidya Sathi assumes no responsibility for a Student's compliance with any agreements with or duties to third parties, applicable laws, rules and regulations. Vidya Sathi reserves the right, at any time and without prior notice, to remove or disable access to any Student for any reason, that Vidya Sathi, in its sole discretion, considers to be objectionable for any reason, in violation of these Terms or Vidya Sathi's then-current Standards, Trademark & Branding Guidelines, or otherwise harmful to the Site, Application or Services.
4.	If you are a Teacher, you understand and agree that your relationship with Vidya Sathi is limited to being a Member and an independent, third-party contractor, and not an employee, agent,         joint- venturer or partner of Vidya Sathi for any reason, and you act exclusively on your own behalf and for your own benefit, and not on behalf of or for the benefit of Vidya Sathi. Vidya Sathi does not control, your offline activities. As a Member you agree not to do anything to create a false impression that you are endorsed by, partnering with, or acting on behalf of or for the benefit of Vidya Sathi, including by inappropriately using any Vidya Sathi intellectual property.
5.	When you enrolll for a Course, you will also be required to upload certain information, such as, uploading a profile picture or verifying phone number. Any Member wishing to enrolll for any of the Courses must meet these requirements.

<h4>9.	No Endorsement </h4>
By using the Site, Application or Services, you agree that any legal remedy or liability that you seek to obtain for actions or omissions of other Members or other third parties will be limited to a claim against the particular Members or other third parties who caused you harm. You agree not to attempt to impose liability on or seek any legal remedy from Vidya Sathi with respect to such actions or omissions.

<h4>10.	Payment Terms </h4>
1.	If an enrolllment is requested for any Course via the Site, Application or Services, We will either pre-approve, confirm or reject the enrolllment request within the period of 7 days from the date of request for enrolllment (‘Enrolllment Request Period’), otherwise the enrolllment request will automatically expire. If We are unable to confirm or decide to reject an enrolllment request within the Enrolllment Request Period, any amounts collected by Vidya Sathi for the requested enrolllment will be refunded to the concerned Student. When We confirm an enrolllment requested by a Student, Vidya Sathi will send the Student an email, text message or message via e-mail and the Application confirming such enrolllment, depending on the selections you make via the Site, Application and Services.
2.	The Course Fees payable will be displayed to the Student before the Student sends an enrolllment request to Vidya Sathi. Upon receipt of the Students enrolllment request, Vidya Sathi may initiate a pre-authorization and/or charge a nominal amount to Student’s Payment Method pursuant to the Payments Terms. If a requested enrolllment is cancelled (before any tuitions are provided), any amounts collected by Vidya Sathi will be refunded to such Student, depending on the selections the Student makes via the Site and Application, and any pre-authorization of Student's Payment Method will be released, if applicable.
3.	Vidya Sathi will collect the Course Fees from Students at the time of the enrolllment request.
4.	Vidya Sathi agrees that no refund will be permitted in respect of tuitions already provided and  in accordance with the cancellation policy reflected in the relevant Listing, (i) permit the Student to cancel the enrolllment and (ii) refund to the Student that portion of the Course Fees specified in the applicable cancellation policy. In case relevant Listing does not have a specified cancellation policy, the refund amount would be pro-rata to the unconsumed portion of the tuition.
5.	You agree that Vidya Sathi through its Site or Application would raise system generated invoice to the Student in relation to the Course for which the Student has enrolled or in relation to any kind of payment done, as per applicable laws. Vidya Sathi will raise invoice for the above which shall be inclusive of all applicable Taxes.
6.	You as a Student agree to pay the Course Fees for any enrolllment requested, in connection with your Vidya Sathi Account. Vidya Sathi will collect the Course Fees pursuant to the Payments Terms.
7.	Once you're confirmed enrolllment transaction is complete you will receive a confirmation email summarizing your confirmed enrolllment.

<h4> 11.	Cancellations and Refunds</h4>
1.	If, as a Student, you wish to cancel a confirmed enrolllment made via the Site or the Application, either prior to or after commencement of the Course, the cancellation policy contained in the applicable Listing will apply to such cancellation provided that no refund will be made in respect of tuitions already provided. Our ability to refund the Course Fees and other amounts charged to you will depend upon the terms of the applicable cancellation policy. Details regarding refunds and cancellation policies are available via the Site and Application. Vidya Sathi will initiate any refunds due pursuant to the Payments Terms.
2.	If We cancel a confirmed enrolllment made via the Site, Services, and Application, (i) Vidya Sathi will refund the Course Fees paid by the Student for such enrolllment to the applicable Student pursuant to the Payments Terms which shall not exceed the total amount paid by the Student.

<h4>12.	Taxes </h4>
You understand and acknowledge that appropriate governmental agencies, departments or authorities (the "Tax Authority") where your office or residence is located may require Taxes to be collected from Students on the amount paid for the Course and to be remitted to the respective Tax Authority. The laws in jurisdictions may vary, but these Taxes may be required to be collected and remitted as a percentage of the Course Fees set by Vidya Sathi.

<h4> 13. User Conduct</h4>
1.	You understand and agree that you are solely responsible for compliance with any and all laws, rules, regulations, and Tax obligations that may apply to your use of the Site, Application, Services and Collective Content. In connection with your use of the Site, Application, Services and Collective Content, you may not and you agree that you will not:
1.	violate any local, state, national, or other law or regulation, or any order of a court, including, without limitation, Tax regulations;
2.	use manual or automated software, devices, scripts, robots, backdoors or other means or processes to access, "scrape," "crawl" or "spider" any web pages or other services contained in the Site, Application, Services or Collective Content;
3.	access or use our Site, Application, Services expose or allow to be used or exposed, any Vidya Sathi Content: (i) that is not publicly displayed by Vidya Sathi in its search results pages or listing pages before an enrolllment is confirmed; (ii) in any way that is inconsistent with the Vidya Sathi’s Privacy Policy or Terms of Service; or (iii) in any way that otherwise violates the privacy rights or any other rights of Vidya Sathi's users or any other third party;
4.	use the Site, Application, Services or Collective Content for any commercial or other purposes that are not expressly permitted by these Terms or in a manner that falsely implies Vidya Sathi endorsement, partnership or otherwise misleads others as to your affiliation with Vidya Sathi;
5.	dilute, tarnish or otherwise harm the Vidya Sathi brand in any way, including through unauthorized use of Collective Content, registering and/or using Vidya Sathi or derivative terms in domain names, trade names, trademarks or other source identifiers, or registering and/or using domains names, trade names, trademarks or other source identifiers that closely imitate or are confusingly similar to Vidya Sathi domains, trademarks, taglines, promotional campaigns or Collective Content;
6.	copy, store or otherwise access or use any information contained on the Site, Application, Services or Collective Content for purposes not expressly permitted by these Terms;
7.	infringe the rights of Vidya Sathi or the rights of any other person or entity, including without limitation, their intellectual property, privacy, publicity or contractual right
8.	interfere with or damage our Site, Application or Services, including, without limitation, through the use of viruses, cancel bots, Trojan horses, harmful code, flood pings, denial-of-service attacks, backdoors, packet or IP spoofing, forged routing or electronic mail address information or similar methods or technology;
9.	use our Site, Application or Services to transmit, distribute, post or submit any information concerning any other person or entity, including without limitation, photographs of others without their permission, personal contact information or credit, debit, calling card or account numbers;
10.	use our Site, Application, Services or Collective Content in connection with the distribution of unsolicited commercial email ("spam") or advertisements unrelated to lodging in a private residence;
11.	"stalk" or harass any other user of our Site, Application, Services or Collective Content, or collect or store any personally identifiable information about any other user other than for purposes of transacting as an Vidya Sathi Student;
12.	register for more than one Vidya Sathi Account or register for an Vidya Sathi Account on behalf of an individual other than yourself, except in case where the parent is registering the account for its child or guardian for its ward;
13.	contact another Member for any purpose other than asking a question related to an Enrolllment, Course, Listing, or the Member's use of the Site, Application and Services;
14.	recruit or otherwise solicit any Member to join third-party services or websites that are competitive to Vidya Sathi, without Vidya Sathi's prior written approval;
15.	recruit or otherwise solicit any Member to join third-party services, applications or websites, without Our prior written approval;
16.	impersonate any person or entity, or falsify or otherwise misrepresent yourself or your affiliation with any person or entity;
17.	use automated scripts to collect information from or otherwise interact with the Site, Application, Services or Collective Content;
18.	use the Site, Application, Services or Collective Content to find a Student and then complete an enrolllment of Course independent of the Site, Application or Services, in order to circumvent the obligation to pay any Fees related to Vidya Sathi's provision of the Services or for any other reasons;
19.	violate these Terms or Vidya Sathi's then-current Policies and or Standards;
20.	engage in disruptive, circumventive, abusive or harassing behaviour in any area or aspect of our Platform, Application, or Services;
21.	post, upload, publish, submit or transmit any Content that: (i) infringes, misappropriates or violates a third party's patent, copyright, trademark, trade secret, moral rights or other intellectual property rights, or rights of publicity or privacy; (ii) violates, or encourages any conduct that would violate, any applicable law or regulation or would give rise to civil liability; (iii) is fraudulent, false, misleading (directly or by omission or failure to update information) or deceptive; (iv) is defamatory, obscene, pornographic, vulgar or offensive; (v) promotes discrimination, bigotry, racism, hatred, harassment or harm against any individual or group; (vi) is violent or threatening or promotes violence or actions that are threatening to any other person; or (vii) promotes illegal or harmful activities or substances;
22.	systematically retrieve data or other content from our Site, Application or Services to create or compile, directly or indirectly, in single or multiple downloads, a collection, compilation, database, directory or the like, whether by manual methods, through the use of bots, crawlers, or spiders, or otherwise;
23.	use, display, mirror or frame the Site, Application, Services or Collective Content, or any individual element within the Site, Application, Services or Collective Content, Vidya Sathi's name, any Vidya Sathi trademark, logo or other proprietary information, or the layout and design of any page or form contained on a page in the Site, Application or Services, without Vidya Sathi's express written consent;
24.	access, tamper with, or use non-public areas of the Site, Application or Services, Vidya Sathi's computer systems, or the technical delivery systems of Vidya Sathi's providers;
25.	attempt to probe, scan, or test the vulnerability of any Vidya Sathi system or network or breach any security or authentication measures;
26.	avoid, bypass, remove, deactivate, impair, descramble, or otherwise circumvent any technological measure implemented by Vidya Sathi or any of Vidya Sathi's providers or any other third party (including another user) to protect the Site, Services, Application or Collective Content;
27.	forge any TCP/IP packet header or any part of the header information in any email or newsgroup posting, or in any way use the Site, Services, Application or Collective Content to send altered, deceptive or false source-identifying information;
28.	attempt to decipher, decompile, disassemble or reverse engineer any of the software used to provide the Site, Services, Application or Collective Content;
29.	advocate, encourage, or assist any third party in doing any of the foregoing; or
30.	accept or make a payment for Course Fees outside Vidya Sathi. If you do so, you acknowledge and agree that you: (i) would be in breach of these Terms; (ii) accept all risks and responsibility for such payment, and (iii) hold Vidya Sathi harmless from any liability for such payment.
2.	Vidya Sathi has the right to investigate and prosecute violations of any of the above to the fullest extent of the law. In addition, and as set in these Terms, Vidya Sathi may take a range of actions against you, including but not limited to deactivating or cancelling Vidya Sathi Account, for a violation of this Section or these Terms.
3.	Vidya Sathi may access, preserve and disclose any of your information if we are required to do so by law, or if we believe in good faith that it is reasonably necessary to (i) respond to claims asserted against Vidya Sathi or to comply with legal process (for example, summons or warrants), (ii) enforce or administer our agreements with users, such as these Terms, (iii) for fraud prevention, risk assessment, investigation, customer support, product development and debugging purposes, or (iv) protect the rights, property or safety of Vidya Sathi, its users, or members of the public.
4.	You acknowledge that Vidya Sathi has no obligation to monitor your access to or use of the Site, Application, Services or Collective Content or to review or edit any Member Content, but has the right to do so for the purpose of operating and improving the Site, Application and Services (including without limitation for fraud prevention, risk assessment, investigation and customer support purposes), to ensure your compliance with these Terms, to comply with applicable law or the order or requirement of a court, administrative agency or other governmental body, to respond to content that it determines is otherwise objectionable or as set forth in these Terms.
5.	Vidya Sathi reserves the right, at any time and without prior notice, to remove or disable access to any Collective Content that Vidya Sathi, at its sole discretion, considers to be objectionable for any reason, in violation of these Terms or otherwise harmful to the Site, Application or Services.

<h4> 14.	Reporting Misconduct</h4>
If anyone who you feel is acting or has acted inappropriately, including but not limited to anyone who (i) engages in offensive, violent or sexually inappropriate behavior, or (ii) engages in any other disturbing conduct, you should immediately report such person to the appropriate authorities and then to Vidya Sathi by contacting us with your police station and report number; provided that your report will not obligate us to take any action beyond that required by law (if any) or cause us to incur any liability to you.

<h4> 15.	Privacy</h4>
In order to provide the services to you we collect some of your Personal Information. We describe our collection and use of personal information in our Privacy Policy. Please review this policy. You must agree to the processing of your personal information as laid out in Vidya Sathi's Privacy Policy (as may be updated from time to time). You agree that Vidya Sathi may disclose personal information provided to us, including the data entered into the Website, if required to by law or government request such as a warrant, or as specified in the Privacy Policy. You must be 18 years or older to use this service. You are responsible for preventing unauthorized access to your account.

<h4> 16.	Intellectual Property Ownership and Rights Notices</h4>
The Site, Application, Services, and Collective Content are protected by copyright, trademark, and other laws of Nepal. You acknowledge and agree that the Site, Application, Services and Collective Content, including all associated intellectual property rights, are the exclusive property of Vidya Sathi and its licensors. You will not remove, alter or obscure any copyright, trademark, service mark or other proprietary rights notices incorporated in or accompanying the Site, Application, Services, or Collective Content. All trademarks, service marks, logos, trade names, and any other proprietary designations of Vidya Sathi used on or in connection with the Site, Application, Services, and Vidya Sathi Content are trademarks or registered trademarks of Vidya Sathi in Nepal and abroad. Trademarks, service marks, logos, trade names and any other proprietary designations of third parties used on or in connection with the Site, Application, Services, and Vidya Sathi Content are used for identification purposes only and may be the property of their respective owners. As a Member, you understand and agree that you are bound by the additional Terms, Guidelines and Policies that apply to your use of the Site, Application, Services and Collective Content, including Vidya Sathi's Trademark & Branding Guidelines (as may be updated from time to time).

<h4> 17.	Additional Terms</h4>
Our Site, Application and Services have different products, features and offerings, so sometimes additional terms or product requirements may apply to your use of those products, features or offerings. If additional terms are available for the relevant product or Services you use, those additional terms become part of these Terms.

<h4> 18.	Application License</h4>
Subject to your compliance with these Terms, Vidya Sathi grants you a limited non-exclusive, non-transferable license to download and install a copy of the Application on each mobile device or computer that you own or control and run such copy of the Application solely for your own personal use.

<h4> 19.	Vidya Sathi Content and Member Content License</h4>
1.	Subject to your compliance with these Terms, Vidya Sathi grants you a limited, non-exclusive, non-transferable license, to (a) access and view any Vidya Sathi Content solely for your personal and non-commercial purposes and (b) access and view any Member Content to which you are permitted access, solely for your personal and non-commercial purposes. You have no right to sublicense the license rights granted in this section.
2.	You will not use, copy, adapt, modify, prepare derivative works based upon, distribute, license, sell, transfer, publicly display, publicly perform, transmit, broadcast or otherwise exploit the Site, Application, Services, or Collective Content, except as expressly permitted in these Terms. No licenses or rights are granted to you by implication or otherwise under any intellectual property rights owned or controlled by Vidya Sathi or its licensors, except for the licenses and rights expressly granted in these Terms.

<h4>20.	Member Content </h4>
1.	We may, in our sole discretion, permit you to post, upload, publish, submit or transmit Member Content. By making available any Member Content on or through the Site, Application, Services, or through Vidya Sathi promotional campaigns, you hereby grant to Vidya Sathi a worldwide, irrevocable, perpetual (or for the term of the protection), non-exclusive, transferable, royalty-free license, with the right to sublicense, to use, view, copy, adapt, modify, distribute, license, sell, transfer, publicly display, publicly perform, transmit, stream, broadcast, access, view, and otherwise exploit such Member Content on, through, by means of or to promote or market the Site, Application and Services. Vidya Sathi does not claim any ownership rights in any such Member Content and nothing in these Terms will be deemed to restrict any rights that you may have to use and exploit any such Member Content.
2.	You acknowledge and agree that you are solely responsible for all Member Content that you make available through the Site, Applications, Services or through Vidya Sathi promotional campaigns. Accordingly, you represent and warrant that: (i) you either are the sole and exclusive owner of all Member Content that you make available through the Site, Application, Services or through Vidya Sathi promotional campaigns or you have all rights, licenses, consents and releases that are necessary to grant to Vidya Sathi the rights in such Member Content, as contemplated under these Terms; and (ii) neither the Member Content nor your posting, uploading, publication, submission or transmittal of the Member Content or Vidya Sathi's use of the Member Content (or any portion thereof) on, through or by means of the Site, Application, the Services or Vidya Sathi promotional campaigns will infringe, misappropriate or violate a third party's patent, copyright, trademark, trade secret, moral rights or other proprietary or intellectual property rights, or rights of publicity or privacy, or result in the violation of any applicable law or regulation.

<h4> 21.	Hyperlinks</h4>
The Site, Application and Services may contain links to third-party websites or resources. You acknowledge and agree that Vidya Sathi is not responsible or liable for: (i) the availability or accuracy of such websites or resources; or (ii) the content, products, or services on or available from such websites or resources. Links to such websites or resources do not imply any endorsement by Vidya Sathi of such websites or resources or the content, products, or services available from such websites or resources. You acknowledge sole responsibility for and assume all risk arising from your use of any such websites or resources or the Content, products or services on or available from such websites or resources.

<h4> 22.	Feedback</h4>
We welcome and encourage you to provide feedback, comments and suggestions for improvements to the Site, Application and Services ("Feedback"). You may submit Feedback by emailing us, through the "Contact" section of the Site and Application, or by other means of communication. You acknowledge and agree that all Feedback you give us will be the sole and exclusive property of Vidya Sathi and you hereby irrevocably assign to Vidya Sathi and agree to irrevocably assign to Vidya Sathi all of your right, title, and interest in and to all Feedback, including without limitation all worldwide patent, copyright, trade secret, moral and other proprietary or intellectual property rights therein, and waive any moral rights you may have in such Feedback. At Vidya Sathi's request and expense, you will execute documents and take such further acts as Vidya Sathi may reasonably request to assist Vidya Sathi to acquire, perfect, and maintain its intellectual property rights and other legal protections for the Feedback.

<h4>23.	Copyright Policy</h4>
Vidya Sathi respects copyright law and expects its users to do the same. It is Vidya Sathi's policy to terminate in appropriate circumstances the Vidya Sathi Accounts of Members or other account holders who repeatedly infringe or are believed to be repeatedly infringing the rights of copyright holders.

<h4> 24.	Term and Termination, Suspension and Other Measures</h4>
1.	Term
This Agreement shall be effective for till the time Members access or use the Site, Application or Services or by downloading or posting any content from or on the Site, via the Application or through the Services Until such time when you or Vidya Sathi terminate the Agreement as described below.
2.	Termination for convenience
You may terminate this Agreement at any time via the "Cancel Account" feature on the Site or by sending us an email. If you cancel your Vidya Sathi Account, any confirmed enrolllment will be automatically cancelled and any refund will depend upon the terms of the applicable cancellation policy. Without limiting our rights specified below, Vidya Sathi may terminate this Agreement for convenience at any time by giving you 30 days' notice via email to your registered email address.
3.	Termination for breach, suspension and other measures
1.	Vidya Sathi may immediately, without notice terminate this Agreement if (i) you have materially breached these Terms or our Policies, including but not limited to any breach of your warranties outlined in these Terms or breach of the "User Conduct" provisions in these Terms, (ii) you have provided inaccurate, fraudulent, outdated or incomplete information during the Vidya Sathi Account registration, or Listing process or thereafter, (iii) you have violated applicable laws, regulations or third party rights, or (iv) Vidya Sathi believes in good faith that such action is reasonably necessary to protect the safety or property of other Members, Vidya Sathi or third parties, for fraud prevention, risk assessment, security or investigation purposes.
2.	In addition Vidya Sathi may deactivate or delay reviews, or other Member Content, cancel any pending or confirmed enrolllments, limit your use of or access to your Vidya Sathi Account and the Site, Application or Services, temporarily or permanently revoke any special status associated with your Vidya Sathi Account, or temporarily or permanently suspend your Vidya Sathi Account if (i) you have breached these Terms or our Policies, including material and nonmaterial breaches and receiving poor ratings from Students, or (ii) Vidya Sathi believes in good faith that such action is reasonably necessary to protect the safety or property of Members, Vidya Sathi or third parties, for fraud prevention, risk assessment, security or investigation purposes.
3.	In case of non-material breaches and where appropriate, you will be given notice of any measure by Vidya Sathi and an opportunity to resolve the issue to Vidya Sathi's reasonable satisfaction.
4.	Consequences of Termination
1.	If we take any of the measures described above we may (i) communicate to the Students that a pending or confirmed enrolllment has been cancelled, (ii) refund the Students in full for any and all confirmed enrolllments, irrespective of pre-existing cancellation policies, (iii) support the Students, on an exceptional basis, in finding potential alternative Courses, and (iv) you will not be entitled to any compensation for confirmed enrolllments that were cancelled.
2.	If You or We terminate this Agreement, we do not have an obligation to delete or return to you any of your Member Content, including but not limited to any reviews or Feedback. When this Agreement has been terminated, you are not entitled to a restoration of your Vidya Sathi Account or any of your Member Content. If your access to or use of the Site, Application and Services has been limited or your Vidya Sathi Account has been suspended or this Agreement has been terminated by us, you may not register a new Vidya Sathi Account or attempt to access and use the Site, Application and Services through other Vidya Sathi Accounts.

<h4> 25.	Survival</h4>
If you or we terminate this Agreement, the clauses of these Terms that reasonably should survive termination of the Agreement will remain in effect.

<h4> 26.	Disclaimers</h4>
1.	If you choose to use the Site, Application, Services or Collective Content, you do so at your sole risk. You acknowledge and agree that Vidya Sathi does not have an obligation to conduct background or character checks on any Member, but may conduct such background or character checks in its sole discretion. If we choose to conduct such checks, to the extent permitted by applicable law, we disclaim warranties of any kind, either express or implied, that such checks will identify prior misconduct by a user or guarantee that a user will not engage in misconduct in the future.
2.	The Site, Application, Services and Collective Content are provided "as is", without warranty of any kind, either express or implied. Without limiting the foregoing, Vidya Sathi explicitly disclaims any warranties of merchantability, fitness for a particular purpose, quiet enjoyment or non-infringement, and any warranties arising out of course of dealing or usage of trade. Vidya Sathi makes no warranty that the site, application, services, collective content, including, but not limited to, any Courses, will meet your requirements or be available on an uninterrupted, secure, or error-free basis. Vidya Sathi makes no warranty regarding the quality of any Listings, Courses, teachers, Students, the Services or Collective Content or the accuracy, timeliness, truthfulness, completeness or reliability of any collective content obtained through the Site, Application or Services.
3.	No advice or information, whether oral or written, obtained from Vidya Sathi or through the Site, Application, Services or Collective Content, will create any warranty not expressly made herein.
4.	You are solely responsible for all of your communications and interactions with other users of the Site, Application or Services and with other persons with whom you communicate or interact as a result of your use of the Site, Application or Services, including, but not limited to, any Students. You understand that Vidya Sathi does not make any attempt to verify the statements of users of the Site, Application or Services or to review any Course. Vidya Sathi makes no representations or warranties as to the conduct of users of the Site, Application or Services or their compatibility with any current or future users of the Site, Application or Services. You agree to take reasonable precautions in all communications and interactions with other users of the site, application or services and with other persons with whom you communicate or interact as a result of your use of the Site, Application Or Services, including, but not limited to, Students, particularly if you decide to meet offline or in person regardless of whether such meetings are organized by Vidya Sathi. Vidya Sathi explicitly disclaims all liability for any act or omission of any Student or other third party.

<h4> 27.	Limitation of Liability</h4>
1.	You acknowledge and agree that, to the maximum extent permitted by law, the entire risk arising out of your access to and use of the Site, Application, Services and Collective Content, your enrolllment of any Course via the Site, Application and Services, and any contact you have with other users of Vidya Sathi whether in person or online remains with you. Neither Vidya Sathi nor any other party involved in creating, producing, or delivering the Site, Application, Services, Collective Content will be liable for any incidental, special, exemplary or consequential damages, including lost profits, loss of data or loss of goodwill, service interruption, computer damage or system failure or the cost of substitute products or services, or for any damages for personal or bodily injury or emotional distress arising out of or in connection with these terms, from the use of or inability to use the Site, Application, Services or Collective Content, from any communications, interactions or meetings with other users of the Site, Application, or Services or other persons with whom you communicate or interact as a result of your use of the Site, Application, Services, or from your Enrolllment of any Course via the Site, Application And Services, whether based on warranty, contract, tort (including negligence), product liability or any other legal theory, and whether or not Vidya Sathi has been informed of the possibility of such damage, even if a limited remedy set forth herein is found to have failed of its essential purpose.
2.	In no event will Vidya Sathi's aggregate liability arising out of or in connection with these Terms and your use of the Site, Application and Services including, but not limited to, your enrolllment of any course via the Site, Application and Services, or from the use of or inability to use the Site, Application, Services, or Collective Content and in connection with any course or interactions with any other members, exceed the amounts you have paid or owe for enrolllments via the Site, Application and Services as a student in the three (3) month period prior to the event giving rise to the liability. The limitations of damages set forth above are fundamental elements of the basis of the bargain between Vidya Sathi and you.

<h4> 28.	Indemnification</h4>
You agree to release, defend, indemnify, and hold Vidya Sathi and its affiliates and subsidiaries, and their officers, directors, employees and agents, harmless from and against any claims, liabilities, damages, losses, and expenses, including, without limitation, reasonable legal and accounting fees, arising out of or in any way connected with (a) your access to or use of the Site, Application, Services, or Collective Content or your violation of these Terms; (b) your Member Content; (c) your (i) interaction with any Member, (ii) enrolllment of an Course; including but not limited to any injuries, losses, or damages (compensatory, direct, incidental, consequential or otherwise) of any kind arising in connection with or as a result of an enrolllment or attending of a Course.

<h4> 29.	Entire Agreement</h4>
Except as they may be supplemented by additional Vidya Sathi policies, guidelines, standards, or terms for a specific product, feature, service or offering, these Terms constitute the entire and exclusive understanding and agreement between Vidya Sathi and you regarding the Site, Application, Services, Collective Content (excluding Payment Services), and any enrolllments made via the Site, Application and Services (excluding Payment Services), and these Terms supersede and replace any and all prior oral or written understandings or agreements between Vidya Sathi and you regarding enrolllments, the Site, Application, Services, and Collective Content (excluding Payment Services).

<h4> 30.	Notices</h4>
Any notices or other communications permitted or required hereunder, including those regarding modifications to these Terms, will be in writing and given by Vidya Sathi (i) via email (in each case to the address that you provide) or (ii) by posting to the Site or via the Application. For notices made by e-mail, the date of receipt will be deemed the date on which such notice is transmitted.

<h4>31.	Governing Law and Jurisdiction</h4>
1.	These Terms and your use of the Services will be interpreted in accordance with the laws of Nepal excluding its rules on conflicts of laws. You and we agree to submit any dispute arising under these Terms to the personal jurisdiction of a court located in Bangalore for any actions for which the parties retain the right to seek injunctive or other equitable relief in a court of competent jurisdiction to prevent the actual or threatened infringement, misappropriation or violation of a party's copyrights, trademarks, trade secrets, patents, or other intellectual property rights.
2.	Any dispute, claim or controversy arising out of or relating to this Terms including the determination of the scope or applicability of this Terms to arbitrate, or your use of the Application or information to which it gives access, shall be determined by arbitration in Nepal, before a sole arbitrator mutually appointed by Members and Vidya Sathi. Arbitration shall be conducted in accordance of Nepal act. The seat of such arbitration shall be kathmandu. All proceedings of such arbitration, including, without limitation, any awards, shall be in the English language. The award shall be final and binding on the parties to the dispute.

<h4> 32.	No Waiver</h4>
The failure of Vidya Sathi to enforce any right or provision of these Terms will not constitute a waiver of future enforcement of that right or provision. The waiver of any such right or provision will be effective only if in writing and signed by a duly authorized representative of Vidya Sathi. Except as expressly set forth in these Terms, the exercise by either party of any of its remedies under these Terms will be without prejudice to its other remedies under these Terms or otherwise. If for any reason a court of competent jurisdiction finds any provision of these Terms invalid or unenforceable, that provision will be enforced to the maximum extent permissible and the other provisions of these Terms will remain in full force and effect.

<h4> 33.	Miscellaneous</h4>
1.	Vidya Sathi shall have no liability of any nature, whether in contract, or otherwise, for any losses whatsoever and howsoever caused, from or in any manner connected with any of the Services provided by Us.
2.	Vidya Sathi is not liable for any failure or delay of performance (or otherwise) arising out of a cause beyond Vidya Sathi’s reasonable control.
3.	You may not assign or transfer these Terms, by operation of law or otherwise, without Vidya Sathi's prior written consent. Any attempt by you to assign or transfer these Terms, without such consent, will be null and of no effect. Vidya Sathi may assign or transfer these Terms, at its sole discretion, without restriction. Subject to the foregoing, these Terms will bind and inure to the benefit of the parties, their successors and permitted assigns.
4.	Vidya Sathi reserves the right at any time and from time to time to modify or discontinue, temporarily or permanently, the Services (or any part thereof) provided by Us with or without notice. You agree that Vidya Sathi shall not be liable to You or to any third party for any modification, suspension or discontinuance of such Services. It is Your responsibility to review these Terms periodically for updates/changes.
5.	You agree not to reproduce, duplicate, copy, sell, resell or exploit for any commercial purposes, any portion of the information provided by us, including any intellectual property rights of Vidya Sathi or any person firm or corporation having posted information for availability through the Services provided by us.
6.	You agree that in the event Your post or Your information violates any provision of this Terms, We shall have the right to refuse to provide You or any person acting on Your behalf, access to the Site and Application, terminate and/ or suspend Your access if applicable in the future.
YOU HAVE READ THESE TERMS OF USE AND AGREE TO ALL OF THE PROVISIONS CONTAINED ABOVE


</pre>
</div>
</body>
@include('frontend.footer')
